layers:
  DEF:
    - [ESC, 1, 2, 3, 4, 5, 6, Y, U, I, O, P]
    - [TAB, Q, W, E, R, T, Y, H, J, K, L, ;]
    - [CAPS, A, S, D, F, G, H, N, M, ",", ., /]
    - [SHIFT, Z, X, X, C, V, B]
    - [CTRL, VOLD, VOLU, ALT, SPACE, M, N]